[package]
name = "websocket"
version = "0.1.0"
authors = ["nlam1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.10.1"
url = "2.1.1"
serde_json = "1.0.53"
native-tls = "0.2.4"
